function gif2TempVisual( Temp, Temp2, delayTime, gifFile )
    global M, global N, global Tmax;
    tempFig = figure();
    set( tempFig, 'Units', 'normalized', 'Position', [0, 0, 1, 1] );
    for h = 1:Tmax
        subplot( 2, 2, 1 );
        surf( 1:M, 1:N, Temp(:, :, h), ...
            'CDataMapping', 'scaled', ...
            'clipping', 'off' ...
        );
        colorbar( 'Location', 'westoutside', ...
                  'Limits', [ 20, 1020 ] ...
        );
        caxis([-900, 700]);
        axis([1, M, 1, N, 0, 1500]);
        view( 0, 90 );
        
        subplot( 2, 2, 2 );
        surf( 1:M, 1:N, Temp(:, :, h), ...
            'CDataMapping', 'scaled', ...
            'clipping', 'off' ...
        );
        caxis([-900, 700]);
        axis([1, M, 1, N, 0, 1500]);
        view( 45, 30 );
        
        subplot( 2, 2, 3 );
        surf( 1:M, 1:N, Temp2(:, :, h), ...
            'CDataMapping', 'scaled', ...
            'clipping', 'off' ...
        );
        colorbar( 'Location', 'westoutside', ...
                  'Limits', [ 20, 1020 ] ...
        );
        caxis([-900, 700]);
        axis([1, M, 1, N, 0, 1500]);
        view( 0, 90 );
        
        subplot( 2, 2, 4 );
        surf( 1:M, 1:N, Temp2(:, :, h), ...
            'CDataMapping', 'scaled', ...
            'clipping', 'off' ...
        );
        caxis([-900, 700]);
        axis([1, M, 1, N, 0, 1500]);
        view( 45, 30 );
        
        f = getframe(gcf);
        [ im, map ] = rgb2ind( f.cdata, 32, 'nodither' );
        if( h == 1 )
            imwrite( im, map, gifFile, ...
                     'WriteMode', 'overwrite' ...
            ); 
        else
            imwrite( im, map, gifFile, ...
                     'DelayTime', delayTime, ...
                     'WriteMode', 'append' ...
            );
        end
        pause( 1/1000 );
    end
    close all;
end

